To create a np_array or Numpy array and see the various form of it np.zero(),np.ones().np.full(),np.empty()

In [1]:
import numpy as np

In [2]:

a =[1,2,3,4]
b=np.array(a)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [21]:
# a=[1,2,3,'5',4.5]
# b=np.array(a,dtype=float)
# print(b)

k =np.ones((2,3),dtype=int)
print(k)

[[1 1 1]
 [1 1 1]]


In [22]:
d=np.ones(3,dtype=str)
print(d)

['1' '1' '1']


In [23]:
f=np.zeros(4,dtype=str)
print(f)

['' '' '' '']


In [24]:
full = np.full((3,3),4,dtype=int)
print(full)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [28]:
a = np.empty(7, dtype = int)
print(a)

[3403141798744321641 7233964313117353519 7305509732338655842
 3558751044176656693 7005406615690437681   32651513910329442
                  97]
