To get the identity of the the list of data for the specific conditions

In [40]:
import numpy as np

In [41]:
a=np.array([1,2,10,40,14,35,11,12,14,2,3,4,25,34])

In [42]:
bool_data=a>10
print(a[bool_data])

[40 14 35 11 12 14 25 34]


In [57]:
bool_data = a[(a>10)&(a<20)]
print(bool_data)

[14 11 12 14]


In [58]:
# We can change all the values that are till the :4 ele in the numpy array it can only cna be used in the Numpy arrays
bool_data[:4]=100
for i in bool_data:
  print(i,end=',')

100,100,100,100,

In [78]:
# We can use the condition to perform the same task

# Let do it with the help of String numpy array
list_str = np.array(['sauhard','Yash','Priyanshu','Suja'])
if list_str[list_str=='Priyanshu']:
  list_str[3:]='YASH'
list_str
list_str_where=np.where(list_str=='Priyanshu')[0]
print(list_str_where)

[2]


In [79]:

import numpy as n 
ar1=n.array([1,2,0,0,4,0])
arr=  n.where(ar1!=0)[0]
# print(arr)
for ele in arr:
    print(ele,end=" ")

0 1 4 

In [80]:
import numpy as n  
arr= n.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
max_count=0
for j in n.arange(len(arr)):
    if arr[j]>max_count:
        max_count=arr[j]
arr[arr==max_count]=0
# print(arr)
for j in arr:
    print(j)

11
2
13
4
15
6
0
8
19


In [81]:
import numpy as np

# Step 1: Define the age and height arrays
age = np.array([15, 17, 19, 20, 14, 21, 16, 19, 13, 20, 22, 23, 21, 16, 18, 19, 20, 15, 17, 18])
height = np.array([156, 144, 180, 162, 152, 157, 154, 155, 151, 150, 158, 179, 126, 182, 183, 154, 159, 160, 172, 149])

# Step 2: Find the indices of heights greater than 155 cm
indices = height > 155

# Step 3: Print the age and height for students whose height is above 155 cm
for i in np.arange(len(age)):
    if indices[i]:  # Check if the corresponding height is above 155
        print(age[i], height[i])  # Print age and height


15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


In [129]:
# Step 1: Create the 2D array
arr = np.array([[21,20,19,23,17],
                [16,15,14,2,12],
                [11,10,9,1,7],
                [6,5,4,78,2]])

# Step 2: Sort the array based on the second column (index 1)
# sorted_arr = arr[arr[:,3].argsort()[::-1]] for descending order
sorted_arr = arr[arr[:,3].argsort()]

# Step 3: Print the sorted 2D array
print(sorted_arr)

[[11 10  9  1  7]
 [16 15 14  2 12]
 [21 20 19 23 17]
 [ 6  5  4 78  2]]
