Various way to create the np.arrray from the given functions

In [59]:
import numpy as np

In [60]:
a = np.arange(start=1,stop=20,step=2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [61]:
#To creata a list of random number 
p=np.random.rand(10,3)
p

array([[0.78184976, 0.87322135, 0.97198827],
       [0.23009207, 0.61525012, 0.27605359],
       [0.2893382 , 0.87072591, 0.55954798],
       [0.38475807, 0.84255144, 0.45007642],
       [0.75995522, 0.54432049, 0.49790356],
       [0.04680557, 0.36894356, 0.3690697 ],
       [0.96454694, 0.52267811, 0.98294286],
       [0.7470927 , 0.76279229, 0.12126979],
       [0.85382014, 0.6741753 , 0.3866598 ],
       [0.81188639, 0.88534808, 0.29213561]])

In [62]:
# Useing the eye() function from the numpy it can create  2D array that help us to form various form of the 2D array
# With the help of various paarmeter like "k" to tell the digonal position and 'like' to get the subclass for the same class array

j = np.eye(3,4,k=3)*10
j

array([[ 0.,  0.,  0., 10.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [63]:
#Useing the function of the np.identity() but cannnot create a 2d array format from this

k=np.identity(3)+2
k

array([[3., 2., 2.],
       [2., 3., 2.],
       [2., 2., 3.]])

In [64]:
# To create a 2D array with the help of the random randit functions()

rand = np.random.randint(10,size=(4,4))
rand

array([[8, 8, 4, 9],
       [2, 9, 6, 7],
       [4, 9, 7, 3],
       [4, 0, 1, 8]], dtype=int32)